### ISSUE TITLE
Change the version scheme

### ISSUE THREAD

**Issue by BeepBot99** [twelve-of-code-official/website#174]
### What solution would you like?

Move 1.1.0 from August 2024 to January 2025. Note that August 2024 would still happen, it just wouldn't be when the features in 1.1.0 are released. This is just a suggestion, you don't have to do it, I just think it might be nice.

### What alternatives have you considered?

Keep the release of Twelve of Code 1.1.0 in August 2024.

#### Pros:

- There is more time to develop 1.1.0.
- We can add even more awesome features to 1.1.0.
- We can say that we will release a new version in January of every year.
- It is more time for people to learn about Twelve of Code.

#### Cons:

- It will take longer for some cool features to be released.
- People will have to wait for longer.
- We might finish early and not have anything to do for a while.

### What page is this for?

Twelve of Code

**Comment by Mesure73L** [comment]
How about this:
- Every year, there is a major release (April 2024 would be 1.0.0, January 2025 would be 1.1.0, etc.)
- Every month, there is a minor release (August 2024 would be 1.0.1, Febuary 2025 would be 1.1.1, etc.)

**Comment by Mesure73L** [comment]
That way, we could still make features for August 2024, but one major update per year.

**Comment by BeepBot99** [comment]
I like that, but not a minor release every month, only when we want to. Also, how about instead of 1.1.0 it is 2.0.0? Then, we can have major releases, minor releases, and builds.

**Comment by Mesure73L** [comment]
How about this:
- One build for every year
- One major release for every month
- Minor releases whenever we want

**Comment by BeepBot99** [comment]
Are you a fucking idiot?
It goes major.minor.build

**Comment by Mesure73L** [comment]
My bad, thanks for informing me politely.

**Comment by BeepBot99** [comment]
Thank you for this!
![image](https://github.com/Mesure73L/mesure.x10.mx/assets/74377508/e04e23bd-0c7f-46aa-9cd4-9b54e3fc1256)

**Comment by BeepBot99** [comment]
Wait so anyway is this suggestion accepted?

**Comment by BeepBot99** [comment]
> Wait so anyway is this suggestion accepted?

You're so mad you didn't even read what I said.

**Comment by Mesure73L** [comment]
> > Wait so anyway is this suggestion accepted?
> 
> You're so mad you didn't even read what I said.

I did, I just decided to ignore it because you don't know how to be respectful.

**Comment by Mesure73L** [comment]
So is my idea good?

**Comment by BeepBot99** [comment]
How about this:
1. It starts at 1.0.0
2. Minor releases whenever we want, like for a single feature. A minor release would go from 1.1.0 to 1.2.0. Minor releases, when released, are always released on the first of a month.
3. Major releases every year. So, it would go from 1.0.0 to 2.0.0.
4. Builds for bugfixes. So, it would go from 1.0.0 to 1.0.1.

**Comment by Mesure73L** [comment]
How about this:
1. It starts at 1.0.0. (Initial release)
3. Minor releases on the first of every month.
   1. Minor releases can be as big as a completely new feature or as small as just making the challenges.
   2. Minor releases only release on the first of every month.
4. Major releases every year.
   1. Major releases only release at the start of the year.
   2. Same things from minor releases apply.
5. Builds for bugfixes or small features that don't affect the challenge very much but are good to have (QoL features).
   1. Builds should not be very big.
   2. Builds can be released whenever.
   3. Examples of things builds can have:
       - Bugfixes
       - Challenges (if we can't make all 3 in time)
       - Small features (e.g. new setting that doesn't affect the challenge very much)
       - Typo fixes
       - Any other small thing

**Comment by BeepBot99** [comment]
No, I think challenges being released should always be builds instead of minor releases unless there is a minor release at the same time. Other than that, it is good.

**Comment by Mesure73L** [comment]
> No, I think challenges being released should always be builds instead of minor releases unless there is a minor release at the same time. Other than that, it is good.

Oh yeah, I forgot to remove that from the minor releases, my bad. This is the official Twelve of Code version scheme now.

**Comment by Mesure73L** [comment]
Oh nevermind, in that I meant like the challenges that we make at the start of the month. Mid-month challenges will be builds.

**Comment by BeepBot99** [comment]
No, what I'm saying is it only goes from 1.0.0 to 1.1.0 if features are being released other than challenges. If only challenges are being released, no matter when they are, then it should go from 1.0.0 to 1.0.1.

**Comment by Mesure73L** [comment]
> No, what I'm saying is it only goes from 1.0.0 to 1.1.0 if features are being released other than challenges. If only challenges are being released, no matter when they are, then it should go from 1.0.0 to 1.0.1.

I don't agree with that. I think to make it more organized, we should have the first of every month be a new minor update.

**Comment by BeepBot99** [comment]
If you care about organization, how about challenges just aren't any update? If you want a comparison, it is like the Minecraft marketplace. There isn't a new Minecraft update every time there is a new thing on the marketplace.

**Comment by Mesure73L** [comment]
No, every time Twelve of Code changes there will be some type of update. Minecraft marketplace is (probably) connected to a database to get everything on the marketplace, and so it doesn't need a new update because the only thing that changed is the list on the database. Twelve of Code challenges will be added to the code, therefore it needs an update.

**Comment by Mesure73L** [comment]
If you want to make comparisons, please make comparisons that are actually fair.

**Comment by BeepBot99** [comment]
You can do whatever you want. This is your challenge, and you have the final say. However, I do think there should be some way to differentiate between challenges being released and an actual update to the experience. I think challenges being released should be independent to updates actually updating the website.

**Comment by BeepBot99** [comment]
We're not hard-coding the challenges anymore. The version should now be independent of challenges.

**Comment by BeepBot99** [comment]
What about this?
![image](https://github.com/twelve-of-code-official/website/assets/74377508/1db91876-800f-497b-92e9-139ebea37fa1)
And maybe you could have a tooltip when you hover over it that says "Twelve of Code 1.0.0, released on April 1st, 2024"

**Comment by BeepBot99** [comment]
I know this should go in #84 but I really don't care, this is about the version too.

**Comment by Mesure73L** [comment]
Make it say "Version 1.0.0" (optional, but still see how it looks) and make the tooltip just say "Released on April 1, 2024" because if you add "12oC 1.0.0" then thats redundant information.

**Comment by BeepBot99** [comment]
Okay, I can do that. Should I make it instead of you then, because you were assigned to #84?

**Comment by Mesure73L** [comment]
Sure
